---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.16.42
  always_update_cookbooks: true
  data_bags_path: test/integration/default/databags

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[beagle-cluster::default]
      - recipe[beagle-cluster::lusers]
      - recipe[beagle-cluster::lusers]
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/lusers
    attributes:
  - name: slurm
    run_list:
      - recipe[beagle-cluster::default]
      - recipe[beagle-cluster::slurm_core]
    verifier:
      inspec_tests:
        - test/smoke/slurm_core
    attributes:
  - name: daemon
    run_list:
      - recipe[beagle-cluster::default]
      - recipe[beagle-cluster::mounts]
      - recipe[beagle-cluster::slurm_core]
      - recipe[beagle-cluster::slurm_daemon]
    verifier:
      inspec_tests:
        - test/smoke/slurm_core
    attributes:
      "beagle":
        "mounts":
          "/app":
            "device": "fserv:/path"
            "fstype": "nfs"
            "options": "ro"
            "actions": 
              - "enable"
  - name: controller
    run_list:
      - recipe[beagle-cluster::default]
      - recipe[beagle-cluster::slurm_core]
      - recipe[beagle-cluster::slurm_controller]
    verifier:
      inspec_tests:
        - test/smoke/slurm_core
    attributes:
