---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.16.42
  always_update_cookbooks: true
  data_bags_path: test/integration/default/databags

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[beagle-cluster::default]
      - recipe[beagle-cluster::lusers]
      - recipe[beagle-cluster::node]
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/lusers
    attributes:
